#!/usr/bin/env node
/* tests/limit16_js_build_parity.test.mjs — the Node chain, fed the JavaScript-generated LIMIT16 A2L
   geometry instead of the printed geometry file, must still reproduce the PRINTED specimen byte for
   byte: the same G-code (after the header rewrite) and the same Bambu container.

   This is tests/build_parity.test.mjs with one substitution: the geometry comes from
   core/weft_limit16_geometry.mjs (the port of limit16_geometry.py), serialised with its json.dumps
   twin and parsed back, so the chain reads exactly what the port would write to disk. The same
   calls, the same options, the same reference files. No browser, no Python: if this passes, a PC with
   Node alone regenerates the geometry AND builds what the machine printed.
   usage: node tests/limit16_js_build_parity.test.mjs */
import fs from 'node:fs'; import path from 'node:path'; import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { createWeftCore, layersFromGeometry, gcodeText, fixHeader, packBambu3mf, zipRead, runGate } from '../core/weft_build.mjs';
import { generateLimit16, toJson } from '../core/weft_limit16_geometry.mjs';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SPEC = path.join(ROOT, 'specimens', '2026-09-04_LIMIT16_A2L_physical');
let fails = 0; const say = (ok, name, detail) => { console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${detail ? ' — ' + detail : ''}`); if (!ok) fails++; };
const sha = b => createHash('sha256').update(b).digest('hex');

const refG = path.join(SPEC, 'LIMIT16_A2L_v1_routeB.gcode'), ref3 = path.join(SPEC, 'PRINT_LIMIT16_A2L_v1.gcode.3mf'), goldenGeo = path.join(SPEC, 'LIMIT16_A2L_v1_geometry.json');
if (!fs.existsSync(refG)) { say(false, 'LIMIT16 specimen files present', 'missing — this test needs the printed specimen folder'); process.exit(1); }

/* the geometry: generated here, not read from the specimen */
const tg = Date.now();
const jsText = toJson(generateLimit16({ machine: 'a2l' }).payload);
const geo = JSON.parse(jsText);
say(geo.layers.length === 40 && geo.summary.name === 'LIMIT16_A2L_v1', 'geometry generated by core/weft_limit16_geometry.mjs', `${geo.layers.length} layers, ${jsText.length} bytes, ${Date.now() - tg} ms`);
if (fs.existsSync(goldenGeo)) {
  const golden = fs.readFileSync(goldenGeo, 'utf8');
  say(true, 'note: JS geometry vs the printed geometry file', golden === jsText ? 'byte-identical' : `${jsText.length} vs ${golden.length} bytes (the printed file predates the membrane-contract cap keys; numeric identity is held by tests/limit16_geom_parity.test.mjs)`);
}

/* the chain, exactly as tests/build_parity.test.mjs runs it on the printed geometry file */
const W = createWeftCore();
const t0 = Date.now();
const report = layersFromGeometry(W, geo, { machine: 'a2l', name: 'LIMIT16_A2L_v1' });
say(report.layers === 988 && report.weldNodes === 1036 && report.unintendedOverlaps === 0 && report.fitsPlate, 'thread rebuilt from the JS geometry', `${report.layers} paths, ${report.weldNodes} welds, ${report.threadLength_m} m, ${Date.now() - t0} ms`);
const txt = await gcodeText(W, path.join(ROOT, 'exports/a2l_start_block_template_2026-09-02.gcode'), path.join(ROOT, 'exports/a2l_end_block_harvested_2026-09-02.gcode'));
const fixed = fixHeader(txt);
const ref = fs.readFileSync(refG, 'utf8');
const same = fixed.text === ref;
let detail = `${fixed.text.length} bytes, sha256 ${sha(fixed.text).slice(0, 16)}`;
if (!same) {
  const a = fixed.text.split('\n'), b = ref.split('\n');
  let i = 0; while (i < a.length && i < b.length && a[i] === b[i]) i++;
  detail += `; ${a.length} vs ${b.length} lines; first differing line ${i + 1}: built ${JSON.stringify(a[i] ?? '<EOF>')} vs printed ${JSON.stringify(b[i] ?? '<EOF>')}`;
}
say(same, 'G-code byte-identical to the printed specimen (after the header rewrite)', detail);
say(fixed.missed.length === 0, 'every header field rewritten', fixed.missed.join(', ') || 'none missed');
const gate = runGate(fixed.text, { bead: 0.45, maxbridge: 16.2, maxcantilever: 4.8, allow: 0.6, minanchor: 0.5, maxCapRadius: 20, maxislands: 1, file: refG });
say(gate.PASS && gate.stats.checked_points === 31016 && gate.stats.first_layer_islands === 1, 'gate verdict on the rebuilt file matches the recorded one', `PASS=${gate.PASS}, ${gate.problem_count} problems, ${gate.stats.checked_points} points`);
if (fs.existsSync(ref3)) {
  const tmp = path.join(os.tmpdir(), `weft_js_build_parity_${process.pid}.gcode.3mf`);
  packBambu3mf(fixed.text, ref3, tmp, { name: 'LIMIT16_A2L_v1.stl', layerHeight: 0.24 });
  const a = zipRead(fs.readFileSync(ref3)), b = zipRead(fs.readFileSync(tmp));
  let diff = 0; for (const e of a) { const m = b.find(x => x.name === e.name); if (!m || Buffer.compare(m.data, e.data) !== 0) { diff++; console.log('   differs:', e.name); } }
  say(diff === 0 && a.length === b.length, 'Bambu container: every member byte-identical to the printed package', `${a.length} members`);
  fs.unlinkSync(tmp);
} else say(true, 'Bambu container check skipped', 'printed .gcode.3mf not present');
console.log(fails ? `\n${fails} check(s) FAILED` : '\nall JS-geometry build parity checks passed');
process.exit(fails ? 1 : 0);
