#!/usr/bin/env node
/* tests/sculpture_js_build_parity.test.mjs — the Node chain, fed the JavaScript-generated GORA geometry
   instead of the Python one, produces the same G-code and the same gate verdicts.

   This is what `node weft.mjs build --geo GORA_geometry.json --machine ender --name GORA_ENDER3V4_X1
   --nostl --allow-experimental-bridge --i-know-the-bead-is-a-guess` does (strategy suma, the Ender's
   ASSUMED bead acknowledged, the declared 60 mm bridge ceiling admitted), run twice in-process:
     A. on the geometry sculpture_geometry.py writes NOW (python3; falls back to the specimen golden,
        which the Python reproduces byte for byte, when python3 is not available),
     B. on the geometry core/weft_sculpture_geometry.mjs writes, serialised with its json.dumps twin
        and parsed back, so the chain reads exactly what the port would write to disk.
   Compared: the thread report, the G-code after the header rewrite (SHA-256, byte for byte), the gate
   at the declared 60 mm ceiling (must be clean), the gate at the evidenced 16 mm ceiling with every
   finding attributed to a declared zone (lintels / horns / crown iris), and the recorded verdicts in
   specimens/2026-09-05_GORA_ENDER3V4_X1_experimental (gate.json, gate_at_16mm.json, report.json).
   The specimen's shipped G-code is not in the repository (only its SHA-256 in manifest.json, from
   the browser builder make_suma.mjs); the SHA of the Node chain's file is printed next to it.
   usage: node tests/sculpture_js_build_parity.test.mjs [--dir DIR] */
import fs from 'node:fs'; import path from 'node:path'; import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { createWeftCore, layersFromGeometry, gcodeText, fixHeader, runGate, loadMachines } from '../core/weft_build.mjs';
import { validateMembraneGeometry } from '../membrane_contract.mjs';
import { generateSculpture, toJson } from '../core/weft_sculpture_geometry.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const argv = process.argv.slice(2);
const opt = (n, d) => { const i = argv.indexOf('--' + n); return i >= 0 ? argv[i + 1] : d; };
const DIR = opt('dir', os.tmpdir());
const PY = process.env.WEFT_PYTHON || 'python3';
const SPEC = path.join(ROOT, 'specimens', '2026-09-05_GORA_ENDER3V4_X1_experimental');
const NAME = 'GORA_ENDER3V4_X1', MACHINE = 'ender';
let fails = 0; const say = (ok, name, detail) => { console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${detail ? ' — ' + detail : ''}`); if (!ok) fails++; };
const sha = b => createHash('sha256').update(b).digest('hex');
const m = loadMachines()[MACHINE];

/* A. the Python-now geometry */
const REF = path.join(DIR, 'sculpture_build_py_GORA_geometry.json');
if (fs.existsSync(REF)) fs.unlinkSync(REF);
let pyText = null, pySource;
const tp = Date.now();
const r = spawnSync(PY, [path.join(ROOT, 'sculpture_geometry.py'), '--variant', 'gora', '--bead', String(m.bead), '--lh', String(m.lh), '--plate', String(m.plate[0]), String(m.plate[1]), '--out', REF], { cwd: ROOT, stdio: ['ignore', 'ignore', 'inherit'] });
if (!r.error && r.status === 0 && fs.existsSync(REF)) { pyText = fs.readFileSync(REF, 'utf8'); pySource = `sculpture_geometry.py now (${Date.now() - tp} ms)`; }
else {
  const golden = path.join(SPEC, `${NAME}_geometry.json`);
  if (!fs.existsSync(golden)) { say(false, 'Python-now geometry', 'python3 failed and the specimen golden is missing'); process.exit(1); }
  pyText = fs.readFileSync(golden, 'utf8'); pySource = 'specimen golden (python3 not available)';
}
say(true, 'Python geometry', `${pySource}, ${pyText.length} bytes`);

/* B. the JavaScript geometry: generated here, not read from the specimen */
const tg = Date.now();
const jsText = toJson(generateSculpture({ variant: 'gora', bead: m.bead, lh: m.lh, plate: m.plate }).payload);
say(jsText.length > 0, 'geometry generated by core/weft_sculpture_geometry.mjs', `${jsText.length} bytes, ${Date.now() - tg} ms`);
say(jsText === pyText, 'JS geometry byte-identical to the Python geometry', jsText === pyText ? '' : `${jsText.length} vs ${pyText.length} bytes`);

/* the chain, as weft.mjs cmdBuild runs it for --geo with strategy suma */
async function chain(text, label){
  const geo = JSON.parse(text);
  const W = createWeftCore();
  validateMembraneGeometry(geo, { rootDir: ROOT, allowExperimental: false, machine: MACHINE });
  const t0 = Date.now();
  const report = layersFromGeometry(W, geo, { name: NAME, machine: MACHINE, grammar: 'staple', tab: 1.0, allowExperimental: false });
  const tThread = Date.now() - t0;
  const txt = await gcodeText(W, path.join(ROOT, m.start), path.join(ROOT, m.end));
  const fixed = fixHeader(txt);
  const A = geo.summary.args;
  const gateOpts = { bead: m.bead, maxbridge: A.maxbridge, maxcantilever: A.maxcantilever, allow: A.allow, minanchor: A.minanchor, maxCapRadius: A.maxCapRadius, maxislands: 1, file: `${NAME}.gcode` };
  const t1 = Date.now();
  const gate = runGate(fixed.text, gateOpts);          // the gate on the final text, before the header rewrite is read back
  const tGate = Date.now() - t1;
  /* the second gate at the evidenced ceiling: every finding must fall in a declared zone */
  const ex = geo.summary.experiments, safe = +ex.evidencedBridge_mm;
  const g2 = runGate(fixed.text, Object.assign({}, gateOpts, { maxbridge: safe }));
  const zones = [];
  for (const l of (ex.lintels || [])) zones.push({ name: `lintel ${l.W_mm}`, z0: l.zLintel - 0.01, z1: l.zLintel + 4 * A.lh + 0.01 });
  for (const h of (ex.horns || [])) zones.push({ name: `horn ${h.P_mm}`, z0: h.zStart - 0.01, z1: h.zEnd + 0.01 });
  if (ex.crown) { const zc = geo.layers.find(l => l.phase === 'crown-iris'); if (zc) zones.push({ name: 'crown iris', z0: zc.zBot - 0.01, z1: 1e9 }); }
  const probs = g2.problems || []; const outside = []; const byZone = {};
  for (const p of probs) { const z = +(p.z ?? NaN); const zone = zones.find(zn => z >= zn.z0 && z <= zn.z1); if (zone) byZone[zone.name] = (byZone[zone.name] || 0) + 1; else outside.push(p); }
  console.log(`  [${label}] thread ${report.layers} paths, ${report.weldNodes} welds, ${report.threadLength_m} m, ${report.size_mm.join('x')} mm, overlaps ${report.unintendedOverlaps} (${tThread} ms); gcode ${fixed.text.length} bytes sha256 ${sha(fixed.text)}; gate@${A.maxbridge} ${gate.PASS ? 'PASS' : 'FAIL'} ${gate.problem_count} problems / ${gate.stats.checked_points} points / ${gate.layers} layers (${tGate} ms); gate@${safe} ${probs.length} findings ${JSON.stringify(byZone)} outside ${outside.length}`);
  return { report, text: fixed.text, gate, g2, byZone, outside, safe, maxbridge: A.maxbridge };
}
const P = await chain(pyText, 'python geometry');
const J = await chain(jsText, 'js geometry');

/* the two chains agree */
const rep = (x) => JSON.stringify({ layers: x.report.layers, weldNodes: x.report.weldNodes, threadLength_m: x.report.threadLength_m, size_mm: x.report.size_mm, unintendedOverlaps: x.report.unintendedOverlaps, seamClosures: x.report.seamClosures, grammarCounts: x.report.grammarCounts });
say(rep(P) === rep(J), 'thread report identical (paths, welds, length, size, overlaps, grammar counts)', rep(J));
const same = P.text === J.text;
let detail = `sha256 ${sha(J.text)} (${J.text.length} bytes)`;
if (!same) { const a = J.text.split('\n'), b = P.text.split('\n'); let i = 0; while (i < a.length && i < b.length && a[i] === b[i]) i++; detail += `; first differing line ${i + 1}: js ${JSON.stringify(a[i] ?? '<EOF>')} vs python ${JSON.stringify(b[i] ?? '<EOF>')}`; }
say(same, 'G-code byte-identical from the JS geometry and from the Python geometry (after the header rewrite)', detail);
say(JSON.stringify(P.gate.stats) === JSON.stringify(J.gate.stats) && P.gate.PASS === J.gate.PASS && P.gate.problem_count === J.gate.problem_count, `gate at the declared ${J.maxbridge} mm ceiling: same verdict and statistics`, `PASS=${J.gate.PASS}, ${J.gate.problem_count} problems, ${J.gate.stats.checked_points} points, ${J.gate.stats.bridges} bridges`);
say(J.gate.PASS && J.gate.problem_count === 0, `gate at the declared ${J.maxbridge} mm ceiling is clean on the JS geometry`, `PASS=${J.gate.PASS}, ${J.gate.problem_count} problems`);
say(JSON.stringify(P.byZone) === JSON.stringify(J.byZone) && P.outside.length === J.outside.length && P.g2.problem_count === J.g2.problem_count, `gate at the evidenced ${J.safe} mm ceiling: same findings and zone attribution`, `${J.g2.problem_count} findings ${JSON.stringify(J.byZone)}, ${J.outside.length} outside the declared zones`);
say(J.outside.length === 0, `every finding at ${J.safe} mm falls inside a declared instrument zone (the build would be admitted)`);

/* the recorded verdicts of the specimen */
const gateFile = path.join(SPEC, `${NAME}_gate.json`), g16File = path.join(SPEC, `${NAME}_gate_at_16mm.json`), repFile = path.join(SPEC, `${NAME}_report.json`), manFile = path.join(SPEC, 'manifest.json');
if (fs.existsSync(gateFile)) {
  const rg = JSON.parse(fs.readFileSync(gateFile, 'utf8'));
  say(rg.PASS === J.gate.PASS && rg.problem_count === J.gate.problem_count && JSON.stringify(rg.stats) === JSON.stringify(J.gate.stats), 'gate at 60 mm matches the recorded specimen gate (verdict and every statistic)', `recorded ${rg.stats.checked_points} points / ${rg.stats.bridges} bridges, PASS=${rg.PASS}`);
}
if (fs.existsSync(g16File)) {
  const r16 = JSON.parse(fs.readFileSync(g16File, 'utf8'));
  say(r16.problem_count === J.g2.problem_count && JSON.stringify(r16.stats) === JSON.stringify(J.g2.stats), 'gate at 16 mm matches the recorded specimen gate (findings and every statistic)', `recorded ${r16.problem_count} findings, long_bridge ${r16.stats.long_bridge}`);
}
if (fs.existsSync(repFile)) {
  const rr = JSON.parse(fs.readFileSync(repFile, 'utf8')).report;
  say(rr.layers === J.report.layers && rr.weldNodes === J.report.weldNodes && rr.threadLength_m === J.report.threadLength_m && JSON.stringify(rr.size_mm) === JSON.stringify(J.report.size_mm) && rr.unintendedOverlaps === J.report.unintendedOverlaps, 'thread report matches the recorded specimen report', `recorded ${rr.layers} paths, ${rr.weldNodes} welds, ${rr.threadLength_m} m, ${rr.size_mm.join('x')} mm, overlaps ${rr.unintendedOverlaps}`);
  const gz = rr.gateAtEvidencedCeiling;
  if (gz) say(gz.findings === J.g2.problem_count && JSON.stringify(gz.byZone) === JSON.stringify(J.byZone) && gz.outsideDeclaredZones === J.outside.length, 'zone attribution at 16 mm matches the recorded report', JSON.stringify(gz.byZone));
}
if (fs.existsSync(manFile)) {
  const man = JSON.parse(fs.readFileSync(manFile, 'utf8'));
  const recorded = man.sha256 && man.sha256[`${NAME}_routeB.gcode`];
  console.log(`  manifest sha256 of the shipped ${NAME}_routeB.gcode (browser builder make_suma.mjs): ${recorded}\n  Node chain sha256 of the G-code built here:                                          ${sha(J.text)}${recorded === sha(J.text) ? '  (identical)' : '  (different builder path; the shipped file is not in the repository)'}`);
}
const out = path.join(DIR, `sculpture_build_js_${NAME}.gcode`);
fs.writeFileSync(out, J.text);
console.log(`  G-code from the JS geometry left at ${out}`);
console.log(fails ? `\n${fails} check(s) FAILED` : '\nall JS-geometry build parity checks passed');
process.exit(fails ? 1 : 0);
