#!/usr/bin/env node
/* WEFT slicer-export wizard (2026-09-16).

   Turns a file sliced by a desktop slicer into a machine-profile CANDIDATE for machines.json, with
   provenance on every value. It never writes machines.json itself: the entry it produces is a proposal
   for a person to read, and its bead is ALWAYS marked assumed — a slicer's line width is a setting, not
   a bead measured in plastic (USAGE.md, "The one rule").

     parseSlicerExport(bufferOrText, { filename })  -> what the export says, and the start/end blocks
     profileFromExport(parsed, { id, label, outDir }) -> a machines.json entry + a `v2` provenance block
     CLI: node core/weft_machine_wizard.mjs FILE --id NAME --label "..." --out DIR

   Detected inputs
     bambu   Bambu Studio: `.gcode.3mf` container (Metadata/plate_1.gcode) or plain .gcode carrying
             `; HEADER_BLOCK_START … ; CONFIG_BLOCK_START … ; key = value … ; CONFIG_BLOCK_END`,
             signature line `; BambuStudio <version>`.
     orca    OrcaSlicer: same block layout, signature `; generated by OrcaSlicer <version> on <date>`.
     prusa   PrusaSlicer / SuperSlicer: `; generated by PrusaSlicer <version> on <date>`, per-layer
             `;LAYER_CHANGE`, trailing `; prusaslicer_config = begin … ; key = value … = end`.
     cura    Cura: `;FLAVOR:<flavor>`, `;Generated with Cura_SteamEngine <version>`, `;Layer height:`,
             per-layer `;LAYER_COUNT:` / `;LAYER:n`, trailing `;SETTING_3 <json fragments>` whose
             concatenation is JSON holding INI-style profiles ([values] = the settings the user changed).
     unknown Anything else that still contains G/M commands (a Klipper or Marlin file, a bare start
             block). Only what can be read from the moves and the M104/M109/M140/M190 lines is reported.
   Refused: STL (ascii or binary), other binary files, a project .3mf with no sliced G-code member, text
   with no G-code commands at all.

   THE START-BLOCK CUT RULE (documented here because the harvested A2L block defines it)
     exports/a2l_start_block_harvested_2026-09-02.gcode ends at `M981 S1 P20000 ;open spaghetti detector`,
     the last line Bambu Studio writes before its first `; CHANGE_LAYER`. Everything before that marker is
     the machine's, including the nozzle load line (`G130 … E20`) — an extruding move. The gate
     (core/weft_gate.js) agrees: every extrusion before the first `; layer` marker is role `startblock`
     and exempt. So:
       1. If the file has a per-layer marker (`; CHANGE_LAYER` Bambu/Orca, `;LAYER_CHANGE` Prusa,
          `;LAYER_COUNT:`/`;LAYER:` Cura, `; layer N` WEFT), the start block is every line before the
          first marker. Purge / load / intro lines inside it stay, even though they extrude.
       2. Without a marker, the start block ends before the first extruding XY move (G0/G1 with E > 0 and
          an X or Y — the gate's own definition) that is NOT a purge. A purge is a run of extruding moves
          (separated only by other G0/G1 lines) that is closed by a `G92 E…` extruder reset before the
          next run. A file that is only a start block (exports/ender_start.gcode) therefore comes back
          whole, with an empty end block.
     Trailing blank lines are trimmed. Nothing else is touched: header statistics stay (fix_header.py /
     fixHeader() rewrite them from the file's own moves), M73 stays, `; EXECUTABLE_BLOCK_START` stays.

   THE END-BLOCK RULE
     From the line after the last extruding XY move to the end of the file, minus: per-layer / per-object
     comments (`; CHANGE_LAYER`, `; Z_HEIGHT:`, `;LAYER_CHANGE`, `;Z:`, `;HEIGHT:`, `;LAYER:`,
     `;TIME_ELAPSED:`, `; FEATURE:`, `;TYPE:`, `; LINE_WIDTH:`, `;WIDTH:`, `;MESH:`, …), wipe sections
     (`; WIPE_START` … `; WIPE_END`, they carry object coordinates), the slicer's own trailing config
     (`; prusaslicer_config`, `;SETTING_3`, `; objects_info`), print statistics (`; filament used …`,
     `; estimated printing time …`) and `; EXECUTABLE_BLOCK_END` (packBambu3mf owns that line, and the
     harvested A2L end block does not carry it). Leading blank lines are trimmed.

   TEMPLATING
     machines.json start blocks carry `{TEMP}` and `{BED}` (core/weft_core.js substitutes them). The
     template is derived from the harvested block exactly as a2l_start_block_template_2026-09-02.gcode
     was derived from a2l_start_block_harvested_2026-09-02.gcode: an `S<n>` on an M104/M109 line whose n
     equals the export's nozzle temperature (normal or first layer) becomes `S{TEMP}`; the same for
     M140/M190 and the bed. Preheat values (`M104 S140 A`), `G150 T220`, `M620.10 … P220` are left alone.
     Klipper macro arguments (`START_PRINT EXTRUDER_TEMP=220 BED_TEMP=60`) get the same treatment.

   Pure JS, node:zlib through core/weft_build.mjs's own zip reader, deterministic. */
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { zipRead, WEFT_ROOT } from './weft_build.mjs';

export const WIZARD_VERSION = '2026-09-16';

export class WizardRefusal extends Error {
  constructor(message, code){ super(message); this.name = 'WizardRefusal'; this.code = code; }
}

/* ---------------------------------------------------------------------------------------------------
   small helpers */
const sha256 = buf => createHash('sha256').update(buf).digest('hex');
const NUM_RE = /-?\d*\.?\d+(?:[eE][-+]?\d+)?/;
/* first number in a string ("0.45mm" -> 0.45, "220,220" -> 220, "50%" -> 50); null when there is none */
function num(s){ if(s == null) return null; const m = NUM_RE.exec(String(s)); return m ? parseFloat(m[0]) : null; }
/* first element of a per-extruder / per-filament list ("220,220" -> "220") */
function firstOf(s){ return s == null ? null : String(s).split(/[,;]/)[0].trim(); }
function isPercent(s){ return typeof s === 'string' && /%\s*$/.test(s.trim()); }
function round(v, d = 3){ return Math.round(v * 10 ** d) / 10 ** d; }

/* G0/G1 word parser — the gate's regex, applied to the line with its comment removed.
   `N123 G1 …` line numbers are tolerated. Returns null for anything that is not a G0/G1. */
const WORDS = /([XYZEF])(-?\d*\.?\d+)/g;
function parseMove(line){
  const body = line.split(';')[0].trim().replace(/^N\d+\s+/i, '');
  if(!/^G0?[01](?:\s|$)/i.test(body)) return null;
  if(/^G1[0-9]/i.test(body)) return null;             // G10 / G17 … are not moves
  const d = { cmd:body.slice(0, 2).toUpperCase() };
  WORDS.lastIndex = 0; let m; while((m = WORDS.exec(body))) d[m[1]] = parseFloat(m[2]);
  return d;
}
/* the gate's definition: E > 0 and an X or Y on the line */
function isExtrudingXY(d){ return !!d && d.E > 0 && ('X' in d || 'Y' in d); }
function isExtruderReset(line){ return /^\s*G92(?:\s|$)/i.test(line) && /\bE-?\d*\.?\d*/i.test(line.split(';')[0]); }

/* ---------------------------------------------------------------------------------------------------
   input sniffing */
function looksLikeStl(buf, filename){
  if(/\.stl$/i.test(filename || '')) return 'extension .stl';
  if(buf.length >= 84){
    const n = buf.readUInt32LE(80);
    if(84 + 50 * n === buf.length && n > 0) return `binary STL (${n} triangles)`;
  }
  const head = buf.subarray(0, 512).toString('latin1');
  if(/^\s*solid\b/.test(head) && /facet\s+normal|endsolid/i.test(buf.subarray(0, 4096).toString('latin1'))) return 'ascii STL';
  return null;
}
function looksBinary(buf){
  const probe = buf.subarray(0, 8192);
  let zeros = 0, high = 0;
  for(let i = 0; i < probe.length; i++){ const b = probe[i]; if(b === 0) zeros++; else if(b > 0x7e && b < 0xc0) high++; }
  return zeros > 0 || high > probe.length * 0.3;
}
const MODEL_EXT = /\.(obj|step|stp|3mf|amf|ply|off|scad|f3d|blend)$/i;

/* ---------------------------------------------------------------------------------------------------
   flavor detection: what each parser keys on */
function detectFlavor(text){
  const head = text.slice(0, 64 * 1024);
  let m;
  if((m = /^;\s*generated by OrcaSlicer\s+(\S+)/mi.exec(head)))
    return { flavor:'orca', slicer:'OrcaSlicer', version:m[1], signature:m[0].trim() };
  if((m = /^;\s*BambuStudio\s+(\S+)/mi.exec(head)) || (m = /^;\s*generated by BambuStudio\s+(\S+)/mi.exec(head)))
    return { flavor:'bambu', slicer:'BambuStudio', version:m[1], signature:m[0].trim() };
  if(/^; HEADER_BLOCK_START/m.test(head) && /^; CONFIG_BLOCK_START/m.test(text))
    return { flavor:'bambu', slicer:'BambuStudio', version:null, signature:'; HEADER_BLOCK_START + ; CONFIG_BLOCK_START (no version line)' };
  if((m = /^;\s*generated by (PrusaSlicer|SuperSlicer|Slic3r PE|Slic3r)\s+(\S+)/mi.exec(head)))
    return { flavor:'prusa', slicer:m[1], version:m[2], signature:m[0].trim() };
  if((m = /^;Generated with (\S+)\s*(\S*)/m.exec(head)) && /^;FLAVOR:/m.test(head)){
    const slicer = /Cura_SteamEngine/i.test(m[1]) ? 'Cura' : m[1];
    return { flavor:'cura', slicer, version:m[2] || null, signature:m[0].trim() };
  }
  return { flavor:'unknown', slicer:null, version:null, signature:null };
}

/* ---------------------------------------------------------------------------------------------------
   config readers — every one returns a flat { key: rawString } map (plus a `keyPrefix` for provenance) */
function readKeyEqValue(lines, from, to, map){
  for(let i = from; i < to; i++){
    const m = /^;\s*([^=\s][^=]*?)\s*=\s?(.*)$/.exec(lines[i]);
    if(m) map[m[1]] = m[2];
  }
}
function bambuConfig(lines){
  const cfg = {}, header = {};
  const cs = lines.findIndex(l => l.startsWith('; CONFIG_BLOCK_START')), ce = lines.findIndex(l => l.startsWith('; CONFIG_BLOCK_END'));
  if(cs >= 0 && ce > cs) readKeyEqValue(lines, cs + 1, ce, cfg);
  const hs = lines.findIndex(l => l.startsWith('; HEADER_BLOCK_START')), he = lines.findIndex(l => l.startsWith('; HEADER_BLOCK_END'));
  if(hs >= 0 && he > hs) for(let i = hs + 1; i < he; i++){ const m = /^;\s*([^:]+?)\s*:\s*(.*)$/.exec(lines[i]); if(m) header[m[1]] = m[2]; }
  return { cfg, header, hasConfigBlock:cs >= 0 && ce > cs };
}
function prusaConfig(lines){
  const cfg = {}, header = {};
  const cs = lines.findIndex(l => /^; prusaslicer_config = begin/.test(l)), ce = lines.findIndex(l => /^; prusaslicer_config = end/.test(l));
  if(cs >= 0 && ce > cs) readKeyEqValue(lines, cs + 1, ce, cfg);
  /* the header's derived extrusion widths: "; external perimeters extrusion width = 0.45mm" */
  for(let i = 0; i < Math.min(lines.length, 60); i++){ const m = /^;\s*(.+?extrusion width)\s*=\s*(.*)$/.exec(lines[i]); if(m) header[m[1]] = m[2]; }
  return { cfg, header, hasConfigBlock:cs >= 0 && ce > cs, configRange:[cs, ce] };
}
function curaConfig(lines){
  const header = {};
  for(let i = 0; i < Math.min(lines.length, 60); i++){
    const m = /^;([A-Za-z][A-Za-z0-9_. ]*?):(.*)$/.exec(lines[i]);
    if(m) header[m[1]] = m[2].trim();
  }
  /* ;SETTING_3 fragments: concatenate, JSON.parse, then read the INI-ish [values] sections */
  const frag = lines.filter(l => l.startsWith(';SETTING_3 ')).map(l => l.slice(';SETTING_3 '.length)).join('');
  const settings = { global:{}, extruders:[] }; let settingsError = null;
  if(frag){
    try{
      const j = JSON.parse(frag);
      const values = txt => { const out = {}; let inValues = false;
        for(const raw of String(txt).split('\n')){ const l = raw.trim();
          if(/^\[.*\]$/.test(l)){ inValues = l === '[values]'; continue; }
          if(!inValues || !l) continue; const eq = l.indexOf('='); if(eq > 0) out[l.slice(0, eq).trim()] = l.slice(eq + 1).trim(); }
        return out; };
      if(j.global_quality) settings.global = values(j.global_quality);
      for(const e of (j.extruder_quality || [])) settings.extruders.push(values(e));
    }catch(e){ settingsError = `;SETTING_3 fragments did not parse as JSON: ${e.message}`; }
  }
  return { header, settings, settingsError };
}

/* ---------------------------------------------------------------------------------------------------
   value extraction. Every extracted value is { value, key, raw } — `key` is the exact source key. */
function pick(map, keys, prefix, transform){
  for(const k of keys){
    if(map[k] == null) continue;
    const raw = String(map[k]).trim();
    if(raw === '' || raw === '""' || raw === 'nil') continue;
    const v = transform ? transform(raw) : num(firstOf(raw));
    if(v == null || (typeof v === 'number' && Number.isNaN(v))) continue;
    return { value:v, key:(prefix ? prefix + ':' : '') + k, raw };
  }
  return null;
}
/* "0x0,330x0,330x320,0x320" (Bambu printable_area, Prusa bed_shape) -> { plate:[w,h], origin:[x,y] } */
function bedShape(raw){
  const pts = String(raw).split(',').map(p => p.trim().split(/x/i).map(Number)).filter(p => p.length === 2 && p.every(Number.isFinite));
  if(pts.length < 3) return null;
  const xs = pts.map(p => p[0]), ys = pts.map(p => p[1]);
  const minx = Math.min(...xs), miny = Math.min(...ys), maxx = Math.max(...xs), maxy = Math.max(...ys);
  return { plate:[round(maxx - minx), round(maxy - miny)], origin:[minx, miny], points:pts };
}
const BED_TYPE_KEY = {           // Bambu/Orca curr_bed_type -> the config key that holds its temperature
  'Cool Plate':'cool_plate_temp', 'Cool Plate (SuperTack)':'supertack_plate_temp', 'Supertack Plate':'supertack_plate_temp',
  'Engineering Plate':'eng_plate_temp', 'High Temp Plate':'hot_plate_temp', 'Textured PEI Plate':'textured_plate_temp',
  'Textured Cool Plate':'textured_cool_plate_temp', 'Smooth Cool Plate':'cool_plate_temp', 'Smooth High Temp Plate':'hot_plate_temp'
};

function valuesBambuOrca(cfg, header){
  const V = {}, P = 'config';
  V.nozzle = pick(cfg, ['nozzle_diameter'], P);
  V.layerHeight = pick(cfg, ['layer_height'], P);
  V.firstLayerHeight = pick(cfg, ['initial_layer_print_height'], P);
  V.lineWidth = pick(cfg, ['line_width', 'outer_wall_line_width', 'inner_wall_line_width'], P);
  V.firstLayerLineWidth = pick(cfg, ['initial_layer_line_width'], P);
  V.temp = pick(cfg, ['nozzle_temperature'], P);
  V.firstLayerTemp = pick(cfg, ['nozzle_temperature_initial_layer'], P);
  const bedType = firstOf(cfg.curr_bed_type || '') || null;
  const bk = bedType && BED_TYPE_KEY[bedType];
  const bedKeys = bk ? [bk] : Object.keys(cfg).filter(k => /_plate_temp$/.test(k)).sort();
  V.bed = pick(cfg, bedKeys.concat(['bed_temperature']), P);
  V.firstLayerBed = pick(cfg, bedKeys.map(k => k + '_initial_layer').concat(['bed_temperature_initial_layer']), P);
  if(bedType && (V.bed || V.firstLayerBed)) V.bedType = { value:bedType, key:'config:curr_bed_type', raw:cfg.curr_bed_type };
  const shape = pick(cfg, ['printable_area', 'bed_shape'], P, bedShape);
  if(shape){ V.plate = { value:shape.value.plate, key:shape.key, raw:shape.raw }; V.bedOrigin = { value:shape.value.origin, key:shape.key, raw:shape.raw }; }
  V.maxZ = pick(cfg, ['printable_height', 'max_print_height'], P);
  V.filamentDiameter = pick(cfg, ['filament_diameter'], P) || pick(header, ['filament_diameter'], 'header');
  V.retractLength = pick(cfg, ['retraction_length'], P);
  V.retractSpeed = pick(cfg, ['retraction_speed'], P);
  V.zHop = pick(cfg, ['z_hop'], P);
  V.firstLayerSpeed = pick(cfg, ['initial_layer_speed'], P);
  V.fanMin = pick(cfg, ['fan_min_speed'], P);
  V.fanMax = pick(cfg, ['fan_max_speed'], P);
  V.fanOffFirstLayers = pick(cfg, ['close_fan_the_first_x_layers'], P);
  V.gcodeFlavor = pick(cfg, ['gcode_flavor'], P, s => s);
  V.printerModel = pick(cfg, ['printer_model'], P, s => s) || pick(cfg, ['printer_settings_id'], P, s => s.replace(/^"|"$/g, ''));
  V.printerSettingsId = pick(cfg, ['printer_settings_id'], P, s => s.replace(/^"|"$/g, ''));
  V.filamentType = pick(cfg, ['filament_type'], P, s => firstOf(s));
  return V;
}
function valuesPrusa(cfg, header){
  const V = {}, P = 'prusaslicer_config';
  V.nozzle = pick(cfg, ['nozzle_diameter'], P);
  V.layerHeight = pick(cfg, ['layer_height'], P);
  const lh = V.layerHeight ? V.layerHeight.value : null;
  const relLH = raw => { const v = num(firstOf(raw)); return v == null ? null : (isPercent(raw) && lh != null ? round(v / 100 * lh, 4) : v); };
  V.firstLayerHeight = pick(cfg, ['first_layer_height'], P, relLH);
  /* widths: a percentage in PrusaSlicer is "of layer height"; the header carries the resolved mm anyway */
  V.lineWidth = pick(header, ['external perimeters extrusion width', 'perimeters extrusion width'], 'header') || pick(cfg, ['external_perimeter_extrusion_width', 'perimeter_extrusion_width', 'extrusion_width'], P, relLH);
  V.firstLayerLineWidth = pick(header, ['first layer extrusion width'], 'header') || pick(cfg, ['first_layer_extrusion_width'], P, relLH);
  V.temp = pick(cfg, ['temperature'], P);
  V.firstLayerTemp = pick(cfg, ['first_layer_temperature'], P);
  V.bed = pick(cfg, ['bed_temperature'], P);
  V.firstLayerBed = pick(cfg, ['first_layer_bed_temperature'], P);
  const shape = pick(cfg, ['bed_shape'], P, bedShape);
  if(shape){ V.plate = { value:shape.value.plate, key:shape.key, raw:shape.raw }; V.bedOrigin = { value:shape.value.origin, key:shape.key, raw:shape.raw }; }
  V.maxZ = pick(cfg, ['max_print_height'], P);
  V.filamentDiameter = pick(cfg, ['filament_diameter'], P);
  V.retractLength = pick(cfg, ['retract_length'], P);
  V.retractSpeed = pick(cfg, ['retract_speed'], P);
  V.zHop = pick(cfg, ['retract_lift'], P);
  V.firstLayerSpeed = pick(cfg, ['first_layer_speed'], P, s => isPercent(s) ? s : num(firstOf(s)));
  V.fanMin = pick(cfg, ['min_fan_speed'], P);
  V.fanMax = pick(cfg, ['max_fan_speed'], P);
  V.fanOffFirstLayers = pick(cfg, ['disable_fan_first_layers'], P);
  V.gcodeFlavor = pick(cfg, ['gcode_flavor'], P, s => s);
  V.printerModel = pick(cfg, ['printer_model'], P, s => s) || pick(cfg, ['printer_settings_id'], P, s => s);
  V.printerSettingsId = pick(cfg, ['printer_settings_id'], P, s => s);
  V.filamentType = pick(cfg, ['filament_type'], P, s => firstOf(s));
  return V;
}
function valuesCura(header, settings){
  const V = {};
  const ext = settings.extruders[0] || {}, glob = settings.global || {};
  const both = Object.assign({}, glob, ext);            // extruder [values] override global ones
  const S = 'SETTING_3:values';
  V.nozzle = pick(both, ['machine_nozzle_size'], S) || pick(header, ['Nozzle diameter'], 'header');
  V.layerHeight = pick(both, ['layer_height'], S) || pick(header, ['Layer height'], 'header');
  V.firstLayerHeight = pick(both, ['layer_height_0'], S);
  V.lineWidth = pick(both, ['wall_line_width_0', 'wall_line_width', 'line_width'], S);
  const ilf = pick(both, ['initial_layer_line_width_factor'], S);
  if(ilf && V.lineWidth) V.firstLayerLineWidth = { value:round(V.lineWidth.value * ilf.value / 100, 4), key:`${V.lineWidth.key} × ${ilf.key}`, raw:`${V.lineWidth.raw} × ${ilf.raw}%` };
  V.temp = pick(both, ['material_print_temperature'], S);
  V.firstLayerTemp = pick(both, ['material_print_temperature_layer_0'], S);
  V.bed = pick(both, ['material_bed_temperature'], S);
  V.firstLayerBed = pick(both, ['material_bed_temperature_layer_0'], S);
  const w = pick(both, ['machine_width'], S), d = pick(both, ['machine_depth'], S);
  if(w && d) V.plate = { value:[w.value, d.value], key:`${w.key} × ${d.key}`, raw:`${w.raw} × ${d.raw}` };
  V.maxZ = pick(both, ['machine_height'], S);
  V.filamentDiameter = pick(both, ['material_diameter'], S);
  V.retractLength = pick(both, ['retraction_amount'], S);
  V.retractSpeed = pick(both, ['retraction_retract_speed', 'retraction_speed'], S);
  const hopOn = pick(both, ['retraction_hop_enabled'], S, s => s);
  V.zHop = pick(both, ['retraction_hop'], S);
  if(V.zHop && hopOn && /false/i.test(hopOn.value)) V.zHop = { value:0, key:`${hopOn.key} = False (retraction_hop ignored)`, raw:hopOn.raw };
  V.firstLayerSpeed = pick(both, ['speed_layer_0', 'speed_print_layer_0'], S);
  V.fanMin = pick(both, ['cool_fan_speed_min', 'cool_fan_speed'], S);
  V.fanMax = pick(both, ['cool_fan_speed_max', 'cool_fan_speed'], S);
  V.fanFirstLayer = pick(both, ['cool_fan_speed_0'], S);
  V.gcodeFlavor = pick(both, ['machine_gcode_flavor'], S, s => s) || pick(header, ['FLAVOR'], 'header', s => s);
  V.printerModel = pick(header, ['TARGET_MACHINE.NAME'], 'header', s => s) || pick(both, ['machine_name'], S, s => s);
  return V;
}
/* unknown flavour: temperatures from the first M104/M109 and M140/M190 with a numeric S, and a layer
   height from the Z steps of the extruding moves (when the file has an object at all) */
function valuesUnknown(lines){
  const V = {};
  for(const l of lines){
    const b = l.split(';')[0];
    let m;
    if(!V.temp && (m = /^\s*M10[49]\s+.*?\bS(\d+(?:\.\d+)?)/i.exec(b)) && +m[1] > 0) V.temp = { value:+m[1], key:`${b.trim().split(/\s+/)[0]} S (start G-code line)`, raw:b.trim() };
    if(!V.bed && (m = /^\s*M1[49]0\s+.*?\bS(\d+(?:\.\d+)?)/i.exec(b)) && +m[1] > 0) V.bed = { value:+m[1], key:`${b.trim().split(/\s+/)[0]} S (start G-code line)`, raw:b.trim() };
    if(!V.temp && (m = /\b(?:EXTRUDER(?:_TEMP)?|HOTEND(?:_TEMP)?|NOZZLE_TEMP|TOOL_TEMP)=(\d+(?:\.\d+)?)/i.exec(b))) V.temp = { value:+m[1], key:'macro argument (start G-code line)', raw:b.trim() };
    if(!V.bed && (m = /\bBED(?:_TEMP)?=(\d+(?:\.\d+)?)/i.exec(b))) V.bed = { value:+m[1], key:'macro argument (start G-code line)', raw:b.trim() };
  }
  return V;
}

/* ---------------------------------------------------------------------------------------------------
   blocks */
const LAYER_MARKER = /^;\s*(CHANGE_LAYER\b|LAYER_CHANGE\b|LAYER_COUNT:|LAYER:|layer\s+-?\d+\b)/;
const PER_LAYER_COMMENT = /^;\s*(CHANGE_LAYER\b|Z_HEIGHT:|LAYER_HEIGHT:|LAYER_CHANGE\b|Z:|HEIGHT:|LAYER:|LAYER_COUNT:|TIME_ELAPSED:|FEATURE:|TYPE:|LINE_WIDTH:|WIDTH:|MESH:|BEFORE_LAYER_CHANGE|AFTER_LAYER_CHANGE|layer num\/total_layer_count:|layer\s+-?\d+\b|\d*\.?\d+\s*$)/;
const TRAILING_META = /^;\s*(EXECUTABLE_BLOCK_END|SETTING_3\b|objects_info\b|prusaslicer_config\b|filament used\b|filament cost\b|total filament\b|estimated (first layer )?printing time\b|End of Gcode\b)/;

function findBlocks(lines){
  const moves = lines.map(parseMove);
  const ext = []; for(let i = 0; i < lines.length; i++) if(isExtrudingXY(moves[i])) ext.push(i);
  const marker = lines.findIndex(l => LAYER_MARKER.test(l));
  let cut, reason, purgeLines = 0;
  if(marker >= 0){
    cut = marker; reason = `first per-layer marker at line ${marker + 1}: ${lines[marker].trim()}`;
    purgeLines = ext.filter(i => i < marker).length;
  }else if(ext.length){
    /* rule 2: runs of extruding moves separated only by G0/G1 lines; a run closed by G92 E… is a purge */
    const runs = []; let run = null, lastIdx = -1;
    for(const i of ext){
      let onlyMoves = run !== null;
      if(run !== null) for(let k = lastIdx + 1; k < i; k++) if(lines[k].trim() && !moves[k]){ onlyMoves = false; break; }
      if(run !== null && onlyMoves) run.end = i; else { run = { start:i, end:i }; runs.push(run); }
      lastIdx = i;
    }
    cut = lines.length; reason = 'no per-layer marker and every extruding run is a purge (closed by G92 E): the file is a start block only';
    for(let r = 0; r < runs.length; r++){
      const next = r + 1 < runs.length ? runs[r + 1].start : lines.length;
      let closed = false; for(let k = runs[r].end + 1; k < next; k++) if(isExtruderReset(lines[k])){ closed = true; break; }
      if(closed){ purgeLines += ext.filter(i => i >= runs[r].start && i <= runs[r].end).length; continue; }
      cut = runs[r].start; reason = `no per-layer marker; first extruding XY move not closed by a G92 E reset, line ${cut + 1}`; break;
    }
  }else{ cut = lines.length; reason = 'no per-layer marker and no extruding move: the file is a start block only'; }
  let s = cut; while(s > 0 && !lines[s - 1].trim()) s--;
  const start = lines.slice(0, s).join('\n');
  const objExt = ext.filter(i => i >= cut);
  const firstExtrude = objExt.length ? objExt[0] : -1, lastExtrude = objExt.length ? objExt[objExt.length - 1] : -1;
  let end = '', endDropped = 0;
  if(lastExtrude >= 0){
    const kept = []; let inWipe = false, inCfg = false;
    for(let i = lastExtrude + 1; i < lines.length; i++){
      const l = lines[i], t = l.trim();
      if(/^;\s*WIPE_START/.test(t)){ inWipe = true; endDropped++; continue; }
      if(/^;\s*WIPE_END/.test(t)){ inWipe = false; endDropped++; continue; }
      if(/^; prusaslicer_config = begin/.test(t)){ inCfg = true; endDropped++; continue; }
      if(/^; prusaslicer_config = end/.test(t)){ inCfg = false; endDropped++; continue; }
      if(inWipe || inCfg || PER_LAYER_COMMENT.test(t) || TRAILING_META.test(t)){ endDropped++; continue; }
      kept.push(l);
    }
    while(kept.length && !kept[0].trim()) kept.shift();
    while(kept.length && !kept[kept.length - 1].trim()) kept.pop();
    end = kept.join('\n');
  }
  return {
    start, end,
    firstExtrudeLine: firstExtrude >= 0 ? firstExtrude + 1 : null,     // 1-based, first extruding XY move of the OBJECT
    lastExtrudeLine: lastExtrude >= 0 ? lastExtrude + 1 : null,
    startCut:{ line:cut + 1, reason, purgeExtrusionsKept:purgeLines },
    layerMarker: marker >= 0 ? lines[marker].trim() : null,
    endDroppedLines:endDropped,
    extrudingMoves:ext.length
  };
}

/* ---------------------------------------------------------------------------------------------------
   parseSlicerExport */
export function parseSlicerExport(input, opts = {}){
  const filename = opts.filename || (typeof input === 'string' ? 'input.gcode' : 'input.bin');
  const buf = Buffer.isBuffer(input) ? input : Buffer.from(String(input), 'utf8');
  if(!buf.length) throw new WizardRefusal(`${filename}: empty file`, 'empty');
  const stl = looksLikeStl(buf, filename);
  if(stl) throw new WizardRefusal(`${filename}: this is an STL (${stl}) — a model, not a sliced file. Slice it in the machine's own slicer and export G-code (Bambu/Orca: "Export plate sliced file" -> .gcode.3mf).`, 'stl');
  const source = { file:filename, sha256:sha256(buf), bytes:buf.length };
  let text, container = null;
  if(buf.length >= 4 && buf[0] === 0x50 && buf[1] === 0x4b && buf[2] === 0x03 && buf[3] === 0x04){
    let entries;
    try{ entries = zipRead(buf); }catch(e){ throw new WizardRefusal(`${filename}: zip container could not be read (${e.message})`, 'zip'); }
    const g = entries.find(x => x.name === 'Metadata/plate_1.gcode') || entries.find(x => /\.gcode$/i.test(x.name));
    if(!g) throw new WizardRefusal(`${filename}: a 3MF container without a sliced G-code member (${entries.length} members: ${entries.map(e => e.name).slice(0, 6).join(', ')}…). A project .3mf is a model; export the SLICED plate (.gcode.3mf).`, 'no-gcode-member');
    text = g.data.toString('utf8');
    container = { members:entries.map(e => e.name), gcodeMember:g.name, gcodeSha256:sha256(g.data),
      hasPlateJson:entries.some(e => e.name === 'Metadata/plate_1.json'), hasSliceInfo:entries.some(e => e.name === 'Metadata/slice_info.config'),
      projectSettings:entries.some(e => e.name === 'Metadata/project_settings.config') };
  }else{
    if(looksBinary(buf)) throw new WizardRefusal(`${filename}: not a text G-code file (binary content${MODEL_EXT.test(filename) ? `, extension ${path.extname(filename)}` : ''})`, 'binary');
    text = buf.toString('utf8');
  }
  const lines = text.split(/\r?\n/);
  if(!lines.some(l => /^\s*(N\d+\s+)?[GM]\d/i.test(l.split(';')[0]) || /^\s*[A-Z_]{4,}(\s|$)/.test(l.split(';')[0])))
    throw new WizardRefusal(`${filename}: no G-code commands found (not a sliced file)`, 'no-gcode');

  const det = detectFlavor(text);
  const warnings = [];
  let values = {}, config = {}, header = {};
  if(det.flavor === 'bambu' || det.flavor === 'orca'){
    const b = bambuConfig(lines); config = b.cfg; header = b.header;
    if(!b.hasConfigBlock) warnings.push('no CONFIG_BLOCK: only the header and the moves could be read');
    values = valuesBambuOrca(config, header);
  }else if(det.flavor === 'prusa'){
    const p = prusaConfig(lines); config = p.cfg; header = p.header;
    if(!p.hasConfigBlock) warnings.push('no "; prusaslicer_config" block: only the header could be read');
    values = valuesPrusa(config, header);
  }else if(det.flavor === 'cura'){
    const c = curaConfig(lines); header = c.header; config = Object.assign({}, c.settings.global, ...c.settings.extruders.map((e, i) => Object.fromEntries(Object.entries(e).map(([k, v]) => [`extruder${i}.${k}`, v]))));
    if(c.settingsError) warnings.push(c.settingsError);
    if(!c.settings.extruders.length && !Object.keys(c.settings.global).length) warnings.push('no ;SETTING_3 profile: Cura only writes the settings the user changed, and here there are none');
    values = valuesCura(header, c.settings);
    warnings.push('Cura ;SETTING_3 carries only the settings changed from the printer definition; anything missing here is in the definition file, not in the export');
  }else{
    values = valuesUnknown(lines);
    warnings.push('no known slicer signature: values come from the moves and the temperature lines only');
  }
  for(const k of Object.keys(values)) if(values[k] == null) delete values[k];
  const blocks = findBlocks(lines);
  /* temperatures the config did not state (Cura writes only what the user changed) are still on the
     start block's own M104/M109/M140/M190 lines — keyed as such, so the reader knows where they came from */
  if(det.flavor !== 'unknown' && (!values.temp || !values.bed)){
    const fromStart = valuesUnknown(blocks.start.split('\n'));
    if(!values.temp && fromStart.temp) values.temp = fromStart.temp;
    if(!values.bed && fromStart.bed) values.bed = fromStart.bed;
  }
  if(blocks.firstExtrudeLine == null) warnings.push('no object in the file (start block only): no end block could be harvested');
  if(det.flavor === 'unknown' && blocks.layerMarker == null && blocks.firstExtrudeLine != null) warnings.push(`start block cut by heuristic (${blocks.startCut.reason}); read it before trusting it`);
  /* layer height from the moves, when the config did not say */
  if(!values.layerHeight && blocks.firstExtrudeLine != null){
    const zs = new Set(); let z = 0;
    for(let i = blocks.startCut.line - 1; i < lines.length; i++){ const d = parseMove(lines[i]); if(!d) continue; if('Z' in d) z = d.Z; if(isExtrudingXY(d)) zs.add(round(z, 3)); }
    const sorted = [...zs].sort((a, b) => a - b); let best = null;
    for(let i = 1; i < sorted.length; i++){ const dz = round(sorted[i] - sorted[i - 1], 3); if(dz > 0.02 && (best == null || dz < best)) best = dz; }
    if(best != null) values.layerHeight = { value:best, key:'derived: smallest Z step between extruding layers', raw:`${sorted.length} distinct Z` };
  }
  return { flavor:det.flavor, slicer:det.slicer, version:det.version, signature:det.signature, values, config, header, blocks, container, source, warnings };
}

/* ---------------------------------------------------------------------------------------------------
   templating: literal temperatures -> {TEMP} / {BED} (see the header comment) */
export function templateStartBlock(start, temps, beds){
  const T = new Set(temps.filter(v => v != null && v > 0)), B = new Set(beds.filter(v => v != null && v > 0));
  const sub = (line, cmdRe, set, tag) => line.replace(cmdRe, (m, pre, val) => set.has(+val) ? `${pre}{${tag}}` : m);
  const replaced = { TEMP:0, BED:0 };
  const out = start.split('\n').map(line => {
    let l = line;
    l = sub(l, /^(\s*M10[49]\b[^;]*?\bS)(\d+(?:\.\d+)?)/i, T, 'TEMP');
    l = sub(l, /^(\s*M1[49]0\b[^;]*?\bS)(\d+(?:\.\d+)?)/i, B, 'BED');
    l = sub(l, /^([A-Z_]+\b[^;]*?\b(?:EXTRUDER(?:_TEMP)?|HOTEND(?:_TEMP)?|NOZZLE_TEMP|TOOL_TEMP)=)(\d+(?:\.\d+)?)/i, T, 'TEMP');
    l = sub(l, /^([A-Z_]+\b[^;]*?\bBED(?:_TEMP)?=)(\d+(?:\.\d+)?)/i, B, 'BED');
    if(l !== line){ if(l.includes('{TEMP}') && !line.includes('{TEMP}')) replaced.TEMP++; if(l.includes('{BED}') && !line.includes('{BED}')) replaced.BED++; }
    return l;
  }).join('\n');
  return { text:out, replaced };
}

/* ---------------------------------------------------------------------------------------------------
   profileFromExport */
const ASSUMED = { plate:[220, 220], maxZ:250, nozzle:0.4, lh:0.2, temp:220, bed:60 };
export function profileFromExport(parsed, opts = {}){
  const id = String(opts.id || '').trim();
  if(!/^[a-z][a-z0-9_-]{0,63}$/i.test(id)) throw new WizardRefusal(`--id "${id}" must be a plain identifier (letters, digits, _ -), it becomes a file name`, 'bad-id');
  const label = opts.label || (parsed.values.printerModel ? parsed.values.printerModel.value : id);
  const outDir = opts.outDir != null ? String(opts.outDir) : '';
  const V = parsed.values, src = parsed.source;
  const prov = {}, needsReview = [];
  const from = (field, v, note) => { prov[field] = { value:v.value, source:'slicer-export', key:v.key, raw:v.raw, file:src.file, sha256:src.sha256 }; if(note) prov[field].note = note; return v.value; };
  const assume = (field, value, why) => { prov[field] = { value, source:'assumed', key:null, file:src.file, sha256:src.sha256, why }; needsReview.push(field); return value; };
  const take = (field, v, fallback, why) => v ? from(field, v) : assume(field, fallback, why);

  prov.label = { value:label, source:opts.label ? 'caller' : (V.printerModel ? 'slicer-export' : 'caller'), key:opts.label ? '--label' : (V.printerModel ? V.printerModel.key : '--id'), file:src.file, sha256:src.sha256 };
  const plate = take('plate', V.plate, ASSUMED.plate, 'the export does not state the bed shape');
  const maxZ = take('maxZ', V.maxZ, ASSUMED.maxZ, 'the export does not state the printable height');
  const nozzle = take('nozzle', V.nozzle, ASSUMED.nozzle, 'the export does not state the nozzle diameter');
  const lh = take('lh', V.layerHeight, ASSUMED.lh, 'the export does not state the layer height');
  const temp = take('temp', V.temp, V.firstLayerTemp ? V.firstLayerTemp.value : ASSUMED.temp, V.firstLayerTemp ? 'only the first-layer nozzle temperature was found; used for every layer' : 'the export does not state a nozzle temperature');
  const bed = take('bed', V.bed, V.firstLayerBed ? V.firstLayerBed.value : ASSUMED.bed, V.firstLayerBed ? 'only the first-layer bed temperature was found; used for every layer' : 'the export does not state a bed temperature');

  /* THE BEAD. Never from an export. A line width is what the slicer was told to aim for; a bead is what
     the machine laid down, measured with calipers on the C1 coupon. So bead is always `assumed`, and the
     evidence says why — even when the number itself came from the export's line width. */
  const beadFrom = V.lineWidth ? `slicer line width ${V.lineWidth.value} (${V.lineWidth.key})` : `nozzle × 1.125 (the A2L measured 0.45 on a 0.4 nozzle)`;
  const bead = V.lineWidth ? round(V.lineWidth.value, 3) : round(nozzle * 1.125, 2);
  const beadEvidence = `NEVER CALIBRATED on this machine; run the C1 coupon (core/weft_c1_calibration.mjs) and put the measured width here. Starting number is ${beadFrom}, which is a slicer setting, not a measured bead.`;
  prov.bead = { value:bead, source:'assumed', key:V.lineWidth ? V.lineWidth.key : null, raw:V.lineWidth ? V.lineWidth.raw : null, file:src.file, sha256:src.sha256, why:beadEvidence };
  needsReview.push('bead');
  const flbFrom = V.firstLayerLineWidth ? `slicer first-layer line width ${V.firstLayerLineWidth.value} (${V.firstLayerLineWidth.key})` : 'bead × 1.15 (the ratio machines.json uses: 0.52/0.45, 0.48/0.42)';
  const firstLayerBead = V.firstLayerLineWidth ? round(V.firstLayerLineWidth.value, 3) : round(bead * 1.15, 2);
  prov.firstLayerBead = { value:firstLayerBead, source:'assumed', key:V.firstLayerLineWidth ? V.firstLayerLineWidth.key : null, raw:V.firstLayerLineWidth ? V.firstLayerLineWidth.raw : null, file:src.file, sha256:src.sha256, why:`same status as bead; starting number is ${flbFrom}` };
  needsReview.push('firstLayerBead');

  /* the rest of what was read, kept beside the entry for the person reading it */
  const extra = ['firstLayerHeight', 'firstLayerTemp', 'firstLayerBed', 'bedType', 'bedOrigin', 'lineWidth', 'firstLayerLineWidth', 'filamentDiameter', 'retractLength', 'retractSpeed', 'zHop', 'firstLayerSpeed', 'fanMin', 'fanMax', 'fanFirstLayer', 'fanOffFirstLayers', 'gcodeFlavor', 'printerModel', 'printerSettingsId', 'filamentType'];
  for(const f of extra) if(V[f]) from(f, V[f]);

  /* blocks */
  const startRaw = parsed.blocks.start, endRaw = parsed.blocks.end;
  const tpl = templateStartBlock(startRaw, [V.temp && V.temp.value, V.firstLayerTemp && V.firstLayerTemp.value], [V.bed && V.bed.value, V.firstLayerBed && V.firstLayerBed.value]);
  const startFile = `${id}_start.gcode`, endFile = `${id}_end.gcode`;
  const join = f => outDir ? (outDir.replace(/[\\/]+$/, '') + '/' + f) : f;
  prov.start = { value:join(startFile), source:'slicer-export', key:`start block rule: ${parsed.blocks.startCut.reason}`, file:src.file, sha256:src.sha256, lines:startRaw ? startRaw.split('\n').length : 0, templated:tpl.replaced, purgeExtrusionsKept:parsed.blocks.startCut.purgeExtrusionsKept };
  if(!tpl.replaced.TEMP && !tpl.replaced.BED) needsReview.push('start (no temperature line could be templated to {TEMP}/{BED})');
  prov.end = { value:join(endFile), source:'slicer-export', key:parsed.blocks.lastExtrudeLine ? `end block rule: after the last extruding XY move (line ${parsed.blocks.lastExtrudeLine}), ${parsed.blocks.endDroppedLines} per-layer/config lines dropped` : 'no object in the export: end block empty', file:src.file, sha256:src.sha256, lines:endRaw ? endRaw.split('\n').length : 0 };
  if(!endRaw) needsReview.push('end (empty: the export had no object after its start block)');

  const route = parsed.container && (parsed.flavor === 'bambu' || parsed.flavor === 'orca') ? 'bambu3mf' : 'gcode';
  prov.route = { value:route, source:'slicer-export', key:parsed.container ? `input is a ${parsed.flavor} .gcode.3mf container` : `input is plain G-code (${parsed.flavor})`, file:src.file, sha256:src.sha256 };

  const entry = {
    label, plate, maxZ, nozzle, bead, beadSource:'ASSUMED', beadEvidence, lh, firstLayerBead, temp, bed,
    start:join(startFile), end:join(endFile), route
  };
  if(route === 'bambu3mf'){
    const rel = path.isAbsolute(src.file) && src.file.startsWith(WEFT_ROOT) ? path.relative(WEFT_ROOT, src.file).split(path.sep).join('/') : src.file;
    entry.containerTemplate = rel;
    const ok = parsed.container.hasPlateJson && parsed.container.hasSliceInfo;
    prov.containerTemplate = { value:rel, source:'slicer-export', key:ok ? 'the export itself: it carries Metadata/plate_1.gcode, plate_1.json and slice_info.config, which packBambu3mf rewrites' : 'the export itself, but plate_1.json / slice_info.config are missing — packBambu3mf needs them', file:src.file, sha256:src.sha256 };
    if(!ok) needsReview.push('containerTemplate');
  }
  entry.v2 = {
    schema:'weft.machine.v2', wizard:WIZARD_VERSION, id,
    source:{ file:src.file, sha256:src.sha256, bytes:src.bytes, flavor:parsed.flavor, slicer:parsed.slicer, version:parsed.version, signature:parsed.signature,
      gcodeMember:parsed.container ? parsed.container.gcodeMember : null, gcodeSha256:parsed.container ? parsed.container.gcodeSha256 : src.sha256 },
    provenance:prov,
    bead:{ w:bead, source:'assumed', evidence:'never calibrated on this machine; run the C1 coupon', startingNumber:beadFrom },
    route,
    start:{ file:startFile, contents:tpl.text, harvested:startRaw, cut:parsed.blocks.startCut, layerMarker:parsed.blocks.layerMarker },
    end:{ file:endFile, contents:endRaw, lastExtrudeLine:parsed.blocks.lastExtrudeLine },
    files:{ [startFile]:tpl.text, [endFile]:endRaw },
    needsReview, warnings:parsed.warnings,
    note:'CANDIDATE. Nothing here has been printed. bead and firstLayerBead are assumed until the C1 coupon is measured on this machine; machines.json paths are repo-relative, adjust start/end/containerTemplate when you copy the entry.'
  };
  return entry;
}

/* ---------------------------------------------------------------------------------------------------
   test helper: the HEADER_BLOCK statistics belong to the print the block came from ("1d 1h 26m 54s" vs
   "45m 36s", 583 vs 40 layers); blank their values so two harvests of the same machine compare equal.
   The slicer version line ("; BambuStudio 02.07.01.62") has no ':' and is kept as it is. */
export function stripHeaderStatistics(text){
  const L = text.split('\n'); let inHdr = false;
  return L.map(l => {
    if(l.startsWith('; HEADER_BLOCK_START')){ inHdr = true; return l; }
    if(l.startsWith('; HEADER_BLOCK_END')){ inHdr = false; return l; }
    return inHdr ? l.replace(/:.*$/, ': #') : l;
  }).join('\n');
}

/* ---------------------------------------------------------------------------------------------------
   CLI */
function summary(entry, parsed){
  const P = entry.v2.provenance, out = [];
  const fmt = v => Array.isArray(v) ? `[${v.join(', ')}]` : (typeof v === 'object' && v !== null ? JSON.stringify(v) : String(v));
  out.push(`WEFT slicer-export wizard ${WIZARD_VERSION}`);
  out.push(`  file     ${parsed.source.file} (${parsed.source.bytes} bytes, sha256 ${parsed.source.sha256.slice(0, 16)}…)`);
  out.push(`  slicer   ${parsed.slicer || '(none recognised)'} ${parsed.version || ''}  flavor=${parsed.flavor}${parsed.container ? `  container member ${parsed.container.gcodeMember}` : ''}`);
  out.push(`  route    ${entry.route}${entry.containerTemplate ? `  containerTemplate=${entry.containerTemplate}` : ''}`);
  out.push('');
  out.push('  field                value                    source          key');
  const order = ['label', 'plate', 'maxZ', 'nozzle', 'bead', 'firstLayerBead', 'lh', 'temp', 'bed', 'start', 'end', 'route', 'containerTemplate'];
  const rest = Object.keys(P).filter(k => !order.includes(k));
  for(const k of order.concat(rest)){
    if(!P[k]) continue; const p = P[k];
    out.push(`  ${k.padEnd(20)} ${fmt(p.value).padEnd(24)} ${p.source.padEnd(15)} ${p.key || '—'}${p.why ? `\n${''.padEnd(63)}why: ${p.why}` : ''}`);
  }
  out.push('');
  out.push(`  start block: ${P.start.lines} lines, ${P.start.purgeExtrusionsKept} purge extrusion(s) kept, templated {TEMP}×${P.start.templated.TEMP} {BED}×${P.start.templated.BED}`);
  out.push(`               cut: ${parsed.blocks.startCut.reason}`);
  out.push(`  end block:   ${P.end.lines} lines${parsed.blocks.lastExtrudeLine ? ` (after line ${parsed.blocks.lastExtrudeLine}, the last extruding move)` : ' (none)'}`);
  if(entry.v2.needsReview.length) out.push(`  NEEDS REVIEW: ${entry.v2.needsReview.join('; ')}`);
  for(const w of parsed.warnings) out.push(`  warning: ${w}`);
  out.push('');
  out.push('  The bead is ASSUMED. A slicer line width is a setting; a bead is measured in plastic. Run the C1 coupon before building for this machine.');
  return out.join('\n');
}

export function runCli(argv){
  const args = { _:[] };
  for(let i = 0; i < argv.length; i++){
    const a = argv[i];
    if(a.startsWith('--')){ const k = a.slice(2); if(i + 1 < argv.length && !argv[i + 1].startsWith('--')) args[k] = argv[++i]; else args[k] = true; }
    else args._.push(a);
  }
  const file = args._[0];
  if(!file || args.help || !args.id || !args.out){
    process.stderr.write('usage: node core/weft_machine_wizard.mjs FILE --id NAME --label "Printer label" --out DIR\n  FILE: a .gcode or .gcode.3mf exported by Bambu Studio, OrcaSlicer, PrusaSlicer or Cura (or any G-code file)\n  writes DIR/<id>_start.gcode, DIR/<id>_end.gcode, DIR/<id>.machine.json — never machines.json\n');
    return 2;
  }
  let parsed, entry;
  try{
    parsed = parseSlicerExport(fs.readFileSync(file), { filename:file });
    entry = profileFromExport(parsed, { id:args.id, label:args.label, outDir:args.out });
  }catch(e){
    if(e instanceof WizardRefusal){ process.stderr.write(`REFUSED (${e.code}): ${e.message}\n`); return 1; }
    throw e;
  }
  const outDir = path.resolve(args.out);
  fs.mkdirSync(outDir, { recursive:true });
  /* on disk the blocks live in their own files; the JSON keeps their names, sizes and hashes, not three copies */
  const onDisk = JSON.parse(JSON.stringify(entry));
  const blockRef = (b, text) => ({ file:b.file, lines:text ? text.split('\n').length : 0, sha256:sha256(Buffer.from(text, 'utf8')), cut:b.cut, layerMarker:b.layerMarker, lastExtrudeLine:b.lastExtrudeLine });
  onDisk.v2.start = blockRef(entry.v2.start, entry.v2.start.contents);
  onDisk.v2.end = blockRef(entry.v2.end, entry.v2.end.contents);
  delete onDisk.v2.files;
  const writes = [[entry.v2.start.file, entry.v2.start.contents], [entry.v2.end.file, entry.v2.end.contents], [`${args.id}.machine.json`, JSON.stringify({ [args.id]:onDisk }, null, 2) + '\n']];
  for(const [name, contents] of writes){
    const target = path.join(outDir, name);
    /* never outside the out dir, never machines.json */
    if(path.dirname(target) !== outDir || path.basename(target) === 'machines.json') throw new Error(`refusing to write ${target}`);
    fs.writeFileSync(target, contents);
  }
  process.stdout.write(summary(entry, parsed) + '\n\n  wrote ' + writes.map(w => path.join(args.out, w[0])).join(', ') + '\n');
  return 0;
}

if(process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)){
  process.exitCode = runCli(process.argv.slice(2));
}
