// Offline review of actual emitted paths. No invented physical surface or sag simulation.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {chromium} from 'playwright';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const input=path.resolve(process.argv[2]),dir=path.dirname(input),D=JSON.parse(fs.readFileSync(input,'utf8'));
const title=D.name.startsWith('RAZMAK')?'RAZMAK':'OBRTAJ',bambu=title==='RAZMAK';
const bead=JSON.parse(fs.readFileSync(path.join(root,'machines.json'),'utf8'))[bambu?'a2l':'ender'].bead;
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${D.name} · WEFT</title>
<style>*{box-sizing:border-box}body{margin:0;background:#e8e4dc;color:#2f3736;font-family:Arial,sans-serif}header{position:absolute;top:38px;left:48px;pointer-events:none}small{letter-spacing:.24em;font-size:13px}h1{font-size:68px;font-weight:500;letter-spacing:-.06em;margin:8px 0}p{font-size:15px;line-height:1.6;margin:3px 0}#canvas{width:100vw;height:100vh;display:block}footer{position:absolute;bottom:32px;left:48px;right:48px;display:flex;justify-content:space-between;align-items:end;gap:24px}button,input{accent-color:#347a78}button{border:1px solid #a8aaa2;background:#e8e4dce6;border-radius:20px;padding:8px 18px;cursor:pointer;color:inherit}#controls{display:flex;align-items:center;gap:10px;background:#e8e4dcde;padding:10px;border-radius:20px}#z{width:140px}#note{max-width:480px;color:#4d5753;font-size:12px}body.capture #controls{visibility:hidden}#error{color:#a11}</style>
<canvas id="canvas"></canvas><header><small>WEFT / SUSPENDED STEPS / 2026—09—19</small><h1>${title}</h1><p>${bambu?'Four displaced levels · Bambu A2L':'Seven revolving levels · Ender'}</p><p>${D.limits[0]} × ${D.limits[1]} × ${D.height} mm design envelope</p><p id="viewnote">Horizontal terraces · one basal frame · closed patterned crown</p><p id="error"></p></header>
<footer><div id="note">Nominal emitted toolpaths. Walls shown every eighth layer for legibility; terrace and crown paths shown throughout. No physical sag is simulated. Drag to rotate; scroll to zoom.</div><div id="controls"><button id="iso">3D</button><button id="front">Front</button><button id="top">Roof</button><label>Height <input id="z" type="range" min="0" max="${D.height}" value="${D.height}" step="0.2"></label></div><p>H${bambu?4:7} / ${bambu?'01':'02'}</p></footer>
<script>${fs.readFileSync(path.join(root,'vendor/three.min.js'),'utf8')}</script>
<script>const D=${JSON.stringify(D)};
const renderer=new THREE.WebGLRenderer({canvas:document.getElementById('canvas'),antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xe8e4dc,1);
const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(),group=new THREE.Group();scene.add(group);
const colors={wall:0x455e5d,terrace:0x367f7c,roof:0x455e5d,art:0xa35f37,base:0x747a72};
const segments=[];
for(const L of D.layers){const a=[],solid=L.phase.startsWith('crown'),z=L.z-D.height/2;for(let i=1;i<L.pts.length;i++){const p=L.pts[i-1],q=L.pts[i];if(solid){const dx=q[0]-p[0],dy=q[1]-p[1],len=Math.hypot(dx,dy);if(len<1e-6)continue;const nx=-dy/len*${bead}/2,ny=dx/len*${bead}/2;const A=[p[0]+nx,z,p[1]+ny],B=[p[0]-nx,z,p[1]-ny],C=[q[0]+nx,z,q[1]+ny],E=[q[0]-nx,z,q[1]-ny];a.push(...A,...B,...C,...B,...E,...C);}else a.push(p[0],z,p[1],q[0],z,q[1]);}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(a,3));const type=L.phase.startsWith('horizontal')?'terrace':L.phase==='crown-art'?'art':L.phase==='crown-grid'?'roof':L.role==='adhesion'?'base':'wall';const line=solid?new THREE.Mesh(geo,new THREE.MeshBasicMaterial({color:colors[type],side:THREE.DoubleSide})):new THREE.LineSegments(geo,new THREE.LineBasicMaterial({color:colors[type]}));line.userData={z:L.z,phase:L.phase};group.add(line);segments.push(line);}
const floor=new THREE.Mesh(new THREE.PlaneGeometry(D.limits[0]*1.18,D.limits[1]*1.18),new THREE.MeshBasicMaterial({color:0xd8d5cd,side:THREE.DoubleSide}));floor.rotation.x=-Math.PI/2;floor.position.y=-D.height/2-.5;scene.add(floor);
let yaw=.66,pitch=.32,zoom=1,roof=false,cut=D.height;
function draw(){const w=innerWidth,h=innerHeight;renderer.setSize(w,h,false);const span=(roof?Math.min(D.limits[0],D.limits[1])*.47:Math.max(D.height,D.limits[0])*1.55)/zoom;camera.left=-span*w/h/2;camera.right=span*w/h/2;camera.top=span/2;camera.bottom=-span/2;camera.near=.1;camera.far=4000;camera.updateProjectionMatrix();const target=new THREE.Vector3(0,roof?D.height/2:8,0);camera.position.set(target.x+900*Math.sin(yaw)*Math.cos(pitch),target.y+900*Math.sin(pitch),target.z+900*Math.cos(yaw)*Math.cos(pitch));camera.lookAt(target);for(const line of segments)line.visible=roof?line.userData.phase.startsWith('crown'):line.userData.z<=cut;floor.visible=!roof;renderer.render(scene,camera);window.__ready=true;}
window.setView=(mode)=>{roof=mode==='top';yaw=mode==='front'?0:.66;pitch=roof?Math.PI/2-.0001:mode==='front'?0:.32;zoom=1;document.getElementById('viewnote').textContent=roof?'Closed crossed grid with a raised ${bambu?'four':'seven'}fold wave drawing':'Horizontal terraces · one basal frame · closed patterned crown';draw();};
for(const id of ['iso','front','top'])document.getElementById(id).onclick=()=>window.setView(id);
document.getElementById('z').oninput=e=>{roof=false;cut=+e.target.value;draw();};let drag=null;const canvas=document.getElementById('canvas');canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;yaw-=(e.clientX-drag[0])*.005;pitch=Math.max(-1.3,Math.min(1.5,pitch+(e.clientY-drag[1])*.005));drag=[e.clientX,e.clientY];draw();};canvas.onpointerup=()=>drag=null;canvas.onwheel=e=>{e.preventDefault();zoom=Math.max(.4,Math.min(4,zoom*Math.exp(-e.deltaY*.001)));draw();};onresize=draw;draw();
</script></html>`;
const out=path.join(dir,'preview.html');fs.writeFileSync(out,html);
const browser=await chromium.launch({headless:true,args:['--allow-file-access-from-files']});
try{const page=await browser.newPage({viewport:{width:1400,height:1600},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto(pathToFileURL(out).href);await page.waitForFunction(()=>window.__ready===true);await page.evaluate(()=>document.body.classList.add('capture'));await page.screenshot({path:path.join(dir,D.name+'_preview.png')});await page.evaluate(()=>window.setView('top'));await page.screenshot({path:path.join(dir,D.name+'_roof.png')});await page.evaluate(()=>window.setView('front'));await page.screenshot({path:path.join(dir,D.name+'_front.png')});if(errors.length)throw Error(errors.join('\n'));console.log(JSON.stringify({html:out,images:['preview','roof','front'],browserErrors:errors}));}finally{await browser.close();}
